/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.0.2-83-g5ea20e4078"
#endif /* AVUTIL_FFVERSION_H */
